version: '3.8'

services:
  secretary-agent:
    
    image: ${IMAGE_TAG}

    container_name: secretary_agent_app
    ports:
      - 8080:5000 
    
    environment:
      GEMINI_API_KEY= ${GEMINI_API_KEY}

    restart: unless-stopped