[project]
name = "secretary-agent"
version = "0.1.0"
description = "Personal secretary"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.108.1",
    "openai-agents>=0.3.1",
]
